### ISSUE TITLE
关于语法缩进

### ISSUE THREAD

**Issue by joe-sky** [hopejs/hope#1]
```js
div()
  com()
    hProp({ text: '设置组件的 props' })
    // 编写组件的默认插槽
    hSlot(() => {
      span()
      $span()
    })
  $com()
$div()
```

想了解作者是如何使上述代码在vscode等ide中格式化后保持这样缩进的格式？

**Comment by zhangzhonghe** [comment]
@joe-sky 这个需要 vscode 插件支持，但现在还没有时间写 vscode 的插件，以后会写的。如果感兴趣的话，也可以帮忙写一下~

**Comment by joe-sky** [comment]
@zhangzhonghe 嗯写vscode插件是可行的。而且觉得写出这种插件的过程也很有意思，对于框架的维护者是件很有成就感的事儿。感觉自建vscode插件这样的工具链可能有以下这些问题：

* 需要建立的工具链往往不只vscode而已，eslint、prettier等可能也都要兼顾到
* 比如可能需要处理如何建立开、闭标签等ts类型之间的关系
* 可能还需要考虑一个含开、闭的完整标签其返回值类型如何定义，有的地方可能会有用

所以感觉现在大多数框架在设计UI描述语法这儿，都是复用如JSX或Vue文件等现有工具链的生态。当然自建工具链并非不可行，也说不定发展成功就有了影响力😃~

**Comment by zhangzhonghe** [comment]
@joe-sky 我现在也在思考怎样才能兼容更多的生态，如 jsx，后端渲染等，现在的代码也可能会重写。
